# Generated by Django 2.2.9 on 2022-04-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ocupacao',
                'verbose_name_plural': 'ocupacaoes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('login', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupacaoes_preceptor', to='api.Ocupacao')),
            ],
            options={
                'verbose_name': 'preceptor',
                'verbose_name_plural': 'preceptores',
                'ordering': ['id'],
                'unique_together': {('id', 'ocupacao')},
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiro_preceptores', to='api.Preceptor')),
            ],
            options={
                'verbose_name': 'roteiro',
                'verbose_name_plural': 'roteiros',
                'ordering': ['id'],
                'unique_together': {('id', 'preceptor')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('texto', models.CharField(max_length=255)),
                ('figura', models.URLField()),
                ('libras', models.URLField()),
                ('audioDescricao', models.URLField()),
                ('titulo', models.CharField(max_length=255)),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_roteiros', to='api.Roteiro')),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
                'ordering': ['id'],
                'unique_together': {('id', 'roteiro')},
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('texto', models.CharField(max_length=255)),
                ('figura', models.URLField()),
                ('libras', models.URLField()),
                ('audioDescricao', models.URLField()),
                ('descricao', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_cards', to='api.Card')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
                'ordering': ['id'],
                'unique_together': {('id', 'card')},
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento_pacientes', to='api.Paciente')),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento_preceptores', to='api.Preceptor')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento_roteiros', to='api.Roteiro')),
            ],
            options={
                'verbose_name': 'roteiro',
                'verbose_name_plural': 'roteiros',
                'ordering': ['id'],
                'unique_together': {('preceptor', 'paciente', 'roteiro')},
            },
        ),
    ]
