# Generated by Django 2.2.9 on 2022-04-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preceptor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
