# Generated by Django 2.2.9 on 2022-04-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_preceptor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['id'], 'verbose_name': 'atendimento', 'verbose_name_plural': 'atendimento'},
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='escolhida',
            field=models.BooleanField(default=False),
        ),
    ]
