# Generated by Django 2.2.9 on 2022-06-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220507_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='preceptor',
            name='avatar',
            field=models.ImageField(default='oi', upload_to='preceptor_avatar'),
            preserve_default=False,
        ),
    ]
