# Generated by Django 2.2.9 on 2022-07-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220724_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preceptor',
            name='avatar',
            field=models.URLField(null=True),
        ),
    ]
